server:
  port: 80

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ticket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379

